[package]
name = "sie4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
codepage-437 = "0.1.0"
colored = "2.0.0"
csv = "1.2.1"
nom = "7.1.3"
prettytable-rs = { version = "0.10.0", default-features = false }
rust_decimal = { version = "1.29.0", features = ["serde"] }
rust_decimal_macros = "1.29.0"
serde = { version = "1.0.156", features = ["derive"] }
time = { version = "0.3.20", features = ["parsing", "macros"] }
