[package]
name = "sie4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
codepage-437 = "0.1.0"
once_cell = "1.17.1"
regex = "1.7.1"
rust_decimal = "1.29.0"
time = { version = "0.3.20", features = ["parsing", "macros"] }
