[package]
name = "sie4-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.3", features = ["derive"] }
rust_decimal = "1.31.0"
sie4.workspace = true
time = "0.3.25"
xlsxwriter = "0.6.0"
